---
name: Hello Workflow

'on':
  push:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v7

      - name: Print greetings
        run: echo "Hello from GitHub Actions..!!"
