---
name: Hello Workflow

'on':
  push:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v7

      - name: Print greetings
        run: echo "Hello from GitHub Actions..!!"

      - name: print current date and time
        run: date

      - name: branch name that triggered the run
        run: echo "${{ github.ref_name }}"

      - name: List the files in repo
        run: ls ${{ github.workspace }}

      - name: invalid command
        run: helloworld  

      - name: Print the runner operating system
        run: |
          echo "Runner OS: ${{ runner.os }}"