name: Self Hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test-self-hosted-runner:
    runs-on: [self-hosted, my-linux-runner]

    steps:
      - name: show runner information
        run: |
          echo "==Operating System=="
          uname -a

          echo "==HostName=="
          hostname

          echo "==Current User=="
          whoami

          echo "==Working Directory=="
          pwd

      - name: Create Test File
        run: |
          echo "This Test file created by GitHub Actions on my self-hosted runner." > github-runner-test.txt

      - name: Verify test file
        run: |
          echo "Verify File Creation"
          ls -l github-runner-test.txt

          if [ -f github-runner-test.txt ]; then
            echo "File created successfully"
          else
            echo "File not created"
            exit 1
          fi

      - name: Display file contents
        run: |
          echo "==File Contents=="
          cat github-runner-test.txt
