name: Smart Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run Linter
        run: echo "Running Linter Check...."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: echo "Running Automated Test Suits.."

  summary:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Print Pipeline Summary
        run: |
          echo "-- Pipeline Summary --"

          # Check Branch Type using Context Variables
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; stream
            echo "Branch Type: Main Branch Push"
          else
            echo "Branch Type: Feature Branch Push (${{ github.ref_name }})"
          fi

          # Print the Commit Message from the Head Commit Context
          echo "Commit Message: ${{ github.event.head_commit.message }}"
